package dev.jasper.remote.transfer;

import dev.jasper.remote.sftp.*;
import dev.jasper.remote.transfer.store.TransferStore;
import java.io.*;
import java.nio.file.*;
import java.security.MessageDigest;
import java.util.*;
import java.util.function.Consumer;

/** Headless bounded-heap probe: generated input and verifying sink, no multi-gigabyte fixture on disk. */
public final class TransferScaleProbe {
    private TransferScaleProbe() {}
    public static void main(String[] args) throws Exception {
        long size=4L*1024*1024*1024+17;
        try(var source=new Generated(true,size);var destination=new Generated(false,size);var db=new TransferStore(Path.of(args[0]))) {
            var job=db.create(new TransferRequest(EndpointRef.local(),List.of("/source"),EndpointRef.local(),"/destination"));
            db.discover(job,List.of(new TransferStore.Discovered("source","/source","/destination/source",source.stat("/source"))));
            var entry=db.entries(job,0,1).getFirst();TransferCopy.copy(db,entry,source,destination,new TransferControl(),(done,total)->{});
            if(db.entry(entry.id()).confirmed()!=size || !destination.published || destination.written!=size || !db.entry(entry.id()).digest().equals(destination.digest)) throw new AssertionError("Long copy mismatch");
            var many=db.create(new TransferRequest(EndpointRef.local(),List.of("/many"),EndpointRef.local(),"/destination"));
            TransferScan.scan(db,many,source,destination,new TransferControl());
            if(db.job(many).totalEntries()!=100_001 || db.entries(many,99_999,200).size()!=2) throw new AssertionError("Discovery mismatch");
            System.out.println("VERIFIED "+size+" bytes; 100001 entries; heap="+Runtime.getRuntime().maxMemory());
        }
    }
    static final class Generated implements FileEndpoint {
        final boolean source;final long size;long written;boolean created,published;String digest;MessageDigest hash=TransferRecovery.sha();
        Generated(boolean source,long size) { this.source=source;this.size=size; }
        public String id() { return source?"generated-source":"generated-destination"; }
        public FileEntry stat(String path) throws IOException {
            if(path.equals("/many") || path.equals("/destination")) return new FileEntry(path.substring(1),FileEntry.Kind.DIRECTORY,0,1000,0755,"","directory");
            if(source) return new FileEntry(path.equals("/source")?"source":FilePaths.name(path),FileEntry.Kind.FILE,path.equals("/source")?size:1,1000,0644,"","source-key");
            if(path.contains(".jasper-") && created || path.equals("/destination/source") && published) return new FileEntry(FilePaths.name(path),FileEntry.Kind.FILE,written,1000,0644,"","destination-key");
            throw new NoSuchFileException(path);
        }
        public void list(String directory,Consumer<FileEntry> visitor) throws IOException { for(int i=0;i<100_000;i++) visitor.accept(new FileEntry("file-"+i,FileEntry.Kind.FILE,1,1000,0644,"","source-"+i)); }
        public InputStream read(String path,long offset) { return new InputStream() {
            long position=offset;
            public int read() { return position++<size?1:-1; }
            public int read(byte[] bytes,int off,int length) { if(position>=size) return -1;int count=(int)Math.min(length,size-position);Arrays.fill(bytes,off,off+count,(byte)1);position+=count;return count; }
        }; }
        public WriteHandle write(String path,long offset,boolean exclusive) throws IOException {
            if(exclusive && created) throw new FileAlreadyExistsException(path);created=true;if(offset!=written) throw new IOException("Wrong offset");
            return new WriteHandle() {
                public void write(int value) throws IOException { if(value!=1) throw new IOException("Corrupt generated byte");hash.update((byte)value);written++; }
                public void write(byte[] bytes,int off,int length) throws IOException {
                    for(int i=off;i<off+length;i++) if(bytes[i]!=1) throw new IOException("Corrupt generated payload");hash.update(bytes,off,length);written+=length;
                }
                public long checkpoint() { return written; }
                public void abort() {}
                public void close() {}
            };
        }
        public void truncate(String path,long length) throws IOException { if(length!=written) throw new IOException("Unexpected truncate"); }
        public void mkdir(String path) {}
        public void symlink(String path,String target) { throw new UnsupportedOperationException(); }
        public void remove(String path,boolean directory) { created=false; }
        public void publish(String temporary,String target,boolean replace) { published=true;created=false;digest=TransferRecovery.hex(hash); }
        public void metadata(String path,long time,int mode) {}
        public String canonical(String path) { return path; }
        public String home() { return "/"; }
        public void abort() {}
        public void close() {}
    }
}
