@background = #fafafa
@foreground = #383a42
@accentColor = #4078f2
@disabledForeground = #696c77
@componentBackground = #fafafa
@buttonBackground = #fafafa
@menuBackground = #fafafa
@menuAcceleratorForeground = #383a42
@selectionBackground = #d5def5
@selectionForeground = #383a42
@selectionInactiveBackground = #d5def5
@selectionInactiveForeground = #383a42
@menuHoverBackground = #e0e4ec
@morayHover = #e0e4ec
@morayBorder = #d0d1d5
Moray.titleBackground = #eaeaeb
Moray.titleForeground = #383a42
Moray.titleInactiveForeground = #696c77
Moray.icon.newTab = #315fc4
Moray.icon.newWindow = #3d7d3b
Moray.icon.split = #87218b
Moray.icon.zoom = #006b96
Moray.icon.find = #986801
Moray.icon.settings = #696c77
Moray.icon.reload = #ca4035

Moray.tabSelectedBackground = #f2f2f3
