@background = #fafafa
@foreground = #383a42
@accentColor = #4078f2
@disabledForeground = #696c77
@componentBackground = #fafafa
@buttonBackground = #fafafa
@menuBackground = #fafafa
@menuAcceleratorForeground = #383a42
@selectionBackground = #d5def5
@selectionForeground = #383a42
@selectionInactiveBackground = #d5def5
@selectionInactiveForeground = #383a42
@menuHoverBackground = #e0e4ec
@morayHover = #e0e4ec
@morayBorder = #d0d1d5
Moray.titleBackground = #eaeaeb
Moray.titleForeground = #383a42
Moray.titleInactiveForeground = #696c77

Moray.tabSelectedBackground = #f2f2f3
Moray.chromeForeground = #383a42
Moray.mutedForeground = #696c77
Moray.tabSelectedForeground = #383a42
Moray.tabUnderline = #696c77
Moray.primaryBackground = #e0e4ec
Moray.primaryBorder = #d0d1d5
Moray.runningForeground = #50a14f
Moray.titleSeparator = #d0d1d5
