@background = #292c34
@foreground = #d3d7df
@accentColor = #61afef
@disabledForeground = #8b929f
@componentBackground = #292c34
@buttonBackground = #292c34
@menuBackground = #292c34
@menuAcceleratorForeground = #abb2bf
@selectionBackground = #3e4451
@selectionForeground = #e6e9ef
@selectionInactiveBackground = #3e4451
@selectionInactiveForeground = #e6e9ef
@menuHoverBackground = #323842
@morayHover = #323842
@morayBorder = #353940
Moray.titleBackground = #23262c
Moray.titleForeground = #848c9b
Moray.titleInactiveForeground = #848c9b

Moray.tabSelectedBackground = #262a2f
Moray.chromeForeground = #d3d7df
Moray.mutedForeground = #848c9b
Moray.tabSelectedForeground = #d3d7df
Moray.tabUnderline = #abb2bf
Moray.primaryBackground = #3a404b
Moray.primaryBorder = #484e59
Moray.runningForeground = #a8c58d
Moray.titleSeparator = #313439
Moray.configSuccessForeground = #a8c58d
Moray.configWarningForeground = #e5c07b
Moray.configErrorForeground = #ff858d
