@background = #282c34
@foreground = #abb2bf
@accentColor = #61afef
@disabledForeground = #8b929f
@componentBackground = #282c34
@buttonBackground = #282c34
@menuBackground = #282c34
@menuAcceleratorForeground = #abb2bf
@selectionBackground = #3e4451
@selectionForeground = #e6e9ef
@selectionInactiveBackground = #3e4451
@selectionInactiveForeground = #e6e9ef
@menuHoverBackground = #323842
@morayHover = #323842
@morayBorder = #3e4451
Moray.titleBackground = #21252b
Moray.titleForeground = #abb2bf
Moray.titleInactiveForeground = #8b929f
